name: Release

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python-poetry-env
      - name: Build
        run: |
          poetry build --no-interaction
      - name: Publish to Pypi
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Deploy docs
        run: poetry run mkdocs gh-deploy --force
